site_name: "API Documentación - Shop"
site_description: "Documentación completa y clara para la API de Shop, "
site_author: "Equipo de Desarrollo Shop"
site_url: "https://tu-dominio.com/docs"

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
  logo: 'assets/logo.png'
  favicon: 'assets/favicon.ico'

nav:
  - Inicio: index.md
  - Introducción: introduction.md
  - Instalación y configuración: instalacion.md
  - Autenticación: authentication.md
  - Endpoints: 
    - Introducción: endpoints.md
    - Usuarios:
      - Editar rol de usuario: users/edit_role.md
      - Listar usuarios: users/find_all.md
      - Buscar usuario por ID: users/find_id.md
    - Productos:
      - Registrar producto: products/register.md
      - Editar stock: products/add_stock.md
      - Buscar producto por categoría: products/find_by_category.md
      - Actualizar producto: products/update.md
      - Eliminar producto: products/delete.md
      - Obtener todos los productos: products/find_all.md
      - Buscar producto por ID: products/find_id.md
    - Categorías:
      - Crear categoría: categories/create.md
      - Listar categorías: categories/find_all.md
      - Buscar categoría por ID: categories/find_id.md
    - Órdenes:
      - Crear orden: orders/create.md
      - Buscar orden por ID: orders/find_by_id.md
      - Buscar órdenes de usuario: orders/find_by_user.md
      - Cancelar orden: orders/cancel.md
    - Pagos:
      - Crear pago: payments/create.md
      - Confirmar reembolso: payments/refund.md
    - Roles:
      - Crear rol: roles/create.md
      - Listar roles: roles/find_all.md
      - Buscar rol por ID: roles/find_id.md

  - Errores comunes: errors.md

extra_css:
  - assets/css/extra.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed

plugins:
  - search
